channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- setuptools
- ase =3.25.0
- defusedxml =0.7.1
- matplotlib-base =3.10.3
- numpy =2.3.1
- pandas =2.3.1
- scipy =1.16.0
- jupyter-book =1.0.0
- hatchling =1.27.0
- hatch-vcs =0.4.0
