channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- setuptools
- ase =3.27.0
- defusedxml =0.7.1
- matplotlib-base =3.10.7
- numpy =2.4.0
- pandas =2.3.3
- scipy =1.16.3
- jupyter-book =1.0.0
- hatchling =1.28.0
- hatch-vcs =0.5.0
