channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- setuptools
- ase =3.27.0
- defusedxml =0.7.1
- matplotlib-base =3.10.8
- numpy =2.4.1
- pandas =3.0.0
- scipy =1.17.0
- jupyter-book =1.0.0
- hatchling =1.28.0
- hatch-vcs =0.5.0
