channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- ase =3.23.0
- defusedxml =0.7.1
- matplotlib-base =3.8.4
- numpy =1.26.4
- pandas =2.2.2
- scipy =1.13.1
- jupyter-book =1.0.0
